apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clouds-web-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: "47.237.77.64.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clouds-web-service
            port:
              number: 80
